# Generated by Django 3.2.9 on 2021-11-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Electric', 'Electric')], max_length=50),
        ),
    ]
