# Generated by Django 3.2.9 on 2021-11-11 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
